#!/bin/sh
#
# $Id: t-adsp-report,v 1.3 2010/09/13 05:23:34 cm-msk Exp $
# 
# verify reporting of ADSP failures

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

export TMPFILE=`mktemp /tmp/opendkim-XXXXXXXXX`

../../miltertest/miltertest -s $srcdir/t-adsp-report.lua || exit 1
# ignore version differences in useragent
diff -I ^User-Agent -u $srcdir/t-adsp-report.txt ${TMPFILE} || exit 1
rm -f ${TMPFILE}
