#!/bin/sh
#
# 
# verify config option Local-ADSP works when an email in a subdomain is sent

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

export TMPFILE=`mktemp /tmp/opendkim-XXXXXXXXX`

../../miltertest/miltertest -s $srcdir/t-local-adsp-subdomain.lua || exit 1
