#!/bin/sh
#
# 
# verify config option Local-ADSP works

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

export TMPFILE=`mktemp /tmp/opendkim-XXXXXXXXX`

../../miltertest/miltertest -s $srcdir/t-local-adsp.lua || exit 1
