#!/bin/sh
#
# $Id: t-lua-speed,v 1.1 2010/07/06 23:43:20 cm-msk Exp $
# 
# simple/simple signing speed test with and without Lua

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

echo ===== signing without Lua
../../miltertest/miltertest -u -s $srcdir/t-lua-speed-nolua.lua
echo ===== signing with Lua
../../miltertest/miltertest -u -s $srcdir/t-lua-speed-lua.lua
