#!/bin/sh
#
# 
# relaxed/simple signing test using KeyTable and SetupPolicyScript

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest $MILTERTESTFLAGS -s $srcdir/t-sign-rs-mixconf.lua
