#!/bin/sh
#
# $Id: t-sign-ss,v 1.3 2010/05/18 02:00:54 cm-msk Exp $
# 
# simple/simple signing test with header field replacement

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest -s $srcdir/t-sign-ss-replace.lua
