#!/bin/sh
#
# 
# simple/simple signing test using macro-based origin selection with value test

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest -s $srcdir/t-sign-ss-macro-value.lua
