#!/bin/sh
#
# 
# simple/simple signing test using macro-based origin selection

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest $MILTERTESTFLAGS -s $srcdir/t-sign-ss-macro.lua
