#!/bin/sh
#
# $Id: t-sign-rs-tables,v 1.1.2.1 2010/05/04 18:16:58 cm-msk Exp $
# 
# relaxed/simple signing test using tables

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest -s $srcdir/t-sign-rs-tables.lua
