#!/bin/sh
#
# $Id: t-sign-rs-tables-token,v 1.1 2010/07/22 23:38:37 cm-msk Exp $
# 
# relaxed/simple signing test using KeyTable with the domain token

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest -s $srcdir/t-sign-rs-tables-token.lua
