#!/bin/sh
#
# $Id: t-sign-rs,v 1.3 2010/05/18 02:00:53 cm-msk Exp $
# 
# relaxed/simple signing test with ATPS

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest -s $srcdir/t-sign-atps.lua
