#!/bin/sh
#
# 
# simple/simple signing test with header field replacement

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest $MILTERTESTFLAGS -s $srcdir/t-sign-ss-replace.lua
