#!/bin/sh
#
# $Id: t-sign-ss,v 1.2.2.1 2010/05/04 18:16:58 cm-msk Exp $
# 
# simple/simple signing test

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest -s $srcdir/t-sign-ss.lua
