#!/bin/sh
#
# $Id: t-verify-ss,v 1.1 2010/09/08 00:55:15 cm-msk Exp $
# 
# simple/simple verifying test with an ATPS result

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest -s $srcdir/t-verify-ss-atps.lua -v -v -v
