#!/bin/sh
#
# $Id: t-verify-unsigned,v 1.1.2.2 2010/05/04 18:16:58 cm-msk Exp $
# 
# unsigned message test

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest -s $srcdir/t-verify-unsigned.lua
