#!/bin/sh
#
# $Id: t-verify-report,v 1.3 2010/09/13 04:34:18 cm-msk Exp $
# 
# verify reporting of failed signatures

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

export TMPFILE=`mktemp /tmp/opendkim-XXXXXXXXX`

../../miltertest/miltertest -s $srcdir/t-verify-report.lua || exit 1
# ignore version differences in useragent and arrival date
diff -I ^User-Agent -I ^Arrival-Date -I ^Date \
	-u $srcdir/t-verify-report.txt ${TMPFILE} || exit 1
rm -f ${TMPFILE}
