#!/bin/sh
#
# 
# verify reporting of failed signatures

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

export TMPFILE=`mktemp /tmp/opendkim-XXXXXXXXX`

../../miltertest/miltertest $MILTERTESTFLAGS -s $srcdir/t-verify-report.lua || exit 1
# ignore version differences in useragent and arrival date
diff -I ^User-Agent -I ^Arrival-Date -I ^Date \
	-u $srcdir/t-verify-report.txt ${TMPFILE} || exit 1
rm -f ${TMPFILE}
