#!/bin/sh
#
# $Id: t-verify-syntax,v 1.1 2010/09/06 06:41:05 grooverdan Exp $
# 
# unspecified protocol family test

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest -s $srcdir/t-verify-syntax.lua
