#!/bin/sh
#
# $Id: t-verify-report,v 1.2 2010/09/12 15:55:43 cm-msk Exp $
# 
# verify reporting of failed signatures

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

export TMPFILE=`mktemp /tmp/opendkim-XXXXXXXXX`

../../miltertest/miltertest -s $srcdir/t-verify-report.lua || exit 1
# ignore version differences in useragent
diff -I ^User-Agent -u t-verify-report.txt ${TMPFILE} || exit 1
rm -f ${TMPFILE}
