#!/bin/sh
#
# $Id: t-verify-ss-bad,v 1.1 2010/09/08 00:55:15 cm-msk Exp $
# 
# simple/simple verifying test (should fail)

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest -s $srcdir/t-verify-ss-bad.lua
