.TH libstrl 3
.SH NAME
.B strlcat(), strlcpy()
\- safer string manipulation functions
.SH SYNOPSIS
#include
.I <sys/types.h>
#include
.I <strl.h>

size_t
.B strlcat
(register char *dst, register const char *src, ssize_t size);

size_t
.B strlcpy
(register char *dst, register const char *src, ssize_t size);

.SH DESCRIPTION
These functions provide safer alternatives to
.I strncat()
and 
.I strncpy(),
respectively.  In each case, the
.I size
parameter indicates the total number of bytes available at
.I dst
and copies or appends only up to the point where
.I dst
is left as a NULL-terminated string.  In both cases, the function
returns the size of the resultant string had the operation succeded.  Thus,
if the return value exceeds
.I size,
then truncation occurred.
.SH NOTES
This is not required on systems that include strlcat() and strlcpy() in their
C libraries.
.SH HISTORY
These functions first appeared in OpenBSD 2.4, and then appeared in FreeBSD
3.3.  This library's source code was originally written at Sendmail, Inc.
sometime after that.
.SH SEE ALSO
strncat(3), strncpy(3)
.SH COPYRIGHT
Copyright (c) 1999-2002, Sendmail, Inc.  All rights reserved.

Copyright (c) 2011, 2012, The Trusted Domain Project.  All rights reserved.
