.TH opendkim-testkey 8 "The OpenDKIM Project"
.SH NAME
.B opendkim-testkey
- DKIM filter installation test
.SH SYNOPSIS
.B opendkim-testkey
-d domain -s selector [-k keypath]
.SH DESCRIPTION
.B opendkim-testkey
verifies the setup of signing and verifying (private and public) keys for use
with
.I opendkim(8).

The test program will read a domain name and selector from the command
line, then query and parse the resulting DKIM key, reporting any errors found.

If a key path is also provided, the test program will read the private key
named and attempt to confirm that the private key specified by
.I keypath
and the public DKIM key retrieved match.
.SH OPTIONS
.TP
.I -d domain
Names the domain in which signing is to be done.  More specifically,
names the domain in which the public key matching the provided private key
will be found.  This parameter must be provided.
.TP
.I -k keypath
Specifies the path to the private key file which should be used for this test.
This parameter is optional.
.TP
.I -s selector
Names the selector within the specified domain whose public key should be
retrieved and compared to the private key provided.  This parameter must
be provided.
.SH NOTES
The test program will also complain if the private key file is readable
by anyone other than the user executing the program.

Other sanity checks may be added in later versions.
.SH VERSION
This man page covers the version of
.I opendkim-testkey
that shipped with version 1.1.2 of
.I OpenDKIM.
.SH COPYRIGHT
Copyright (c) 2007, 2008, Sendmail, Inc. and its suppliers.  All rights
reserved.

Copyright (c) 2009, The OpenDKIM Project.  All rights reserved.
.SH SEE ALSO
.I opendkim(8)
.P
RFC4871 - DomainKeys Identified Mail
