#!/sbin/sh
#
# Start method script for the DKIM milter
#

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin; export PATH

. /lib/svc/share/smf_include.sh

echo "starting opendkim"
opendkim -x /etc/mail/opendkim.conf
echo "started opendkim"
exit $SMF_EXIT_OK

#!/end
