#!/bin/sh
#
# Copyright (c) 2010, The OpenDKIM Project.  All rights reserved.
#
# $Id: opendkim-genstats,v 1.2 2010/09/01 22:51:48 cm-msk Exp $
#
# Script to generate some HTML-ized statistics for OpenDKIM

###
### Setup
###

# Command to perform a MySQL query and output HTML
MYSQL_CMD="/usr/local/bin/mysql --html"

# Database name
DB=opendkim

# Database user
USER=opendkim

# Database user's password
PASSWORD=password

# Where to write the report
OUTPUT=/var/www/docs/opendkim/report.html

###
### NO user-serviceable parts beyond this point
###

MYSQL="$MYSQL_CMD --user=$USER --password=$PASSWORD --database=$DB"

# output a header
cat > $OUTPUT << EOF
<html>
  <head>
   <title>
    OpenDKIM Statistics Report
   </title>
  </head>

  <body>
EOF

echo "<b>OpenDKIM Statistics Report generated at `date` </b> <br>" >> $OUTPUT

echo "<p>Total records (messages) received: <br>" >> $OUTPUT
$MYSQL --execute="select count(*) as count from messages" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Reporting hosts and record counts: <br>" >> $OUTPUT
$MYSQL --execute="select reporters.name as 'reporter', count(*) as 'messages' from messages join reporters on messages.reporter = reporters.id group by messages.reporter order by count(*) desc" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Overall message signature counts: <br>" >> $OUTPUT
$MYSQL --execute="select sigcount, count(*) as messages from messages group by sigcount" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Signature algorithm use: <br>" >> $OUTPUT
$MYSQL --execute="select if(algorithm = 0, 'rsa-sha1', 'rsa-sha256') as 'signing algorithm', count(algorithm) as count from signatures group by algorithm" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Header canonicalization use: <br>" >> $OUTPUT
$MYSQL --execute="select if(hdr_canon = 0, 'simple', 'relaxed') as canonicalization, count(hdr_canon) as count from signatures group by hdr_canon" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Body canonicalization use: <br>" >> $OUTPUT
$MYSQL --execute="select if(body_canon = 0, 'simple', 'relaxed') as canonicalization, count(body_canon) as count from signatures group by body_canon" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Signature properties: <br>" >> $OUTPUT
$MYSQL --execute="select sum(sig_t) as 't=', sum(sig_x) as 'x=', sum(sig_z) as 'z=' from signatures" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Key properties: <br>" >> $OUTPUT
$MYSQL --execute="select sum(key_t) as 't=', sum(key_g) as 'g=', sum(key_g_name) as 'g=name', sum(key_dk_compat) as 'DK compat' from signatures" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>DNSSEC results (see libopendkim/dkim.h): <br>" >> $OUTPUT
$MYSQL --execute="select dnssec as 'DNSSEC code', count(*) as count from signatures group by dnssec order by dnssec" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Overall pass/fail rate for signed mail: <br>" >> $OUTPUT
$MYSQL --execute="select count(*) as signatures, sum(ignored) as ignored, sum(pass) as passed, sum(fail_body) as 'failed(body)' from signatures" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Overall pass/fail rate for signed mail, excluding list traffic: <br>" >> $OUTPUT
$MYSQL --execute="select count(*) as signatures, sum(ignored) as ignored, sum(pass) as passed, sum(fail_body) as 'failed(body)' from signatures join messages on messages.id = signatures.message where messages.mailing_list = 0" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Top five error codes (see libopendkim/dkim.h): <br>" >> $OUTPUT
$MYSQL --execute="select sigerror, count(*) as instances from signatures where not sigerror = 0 and not sigerror = 28 group by sigerror order by instances desc limit 5" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>MLM/non-MLM signature comparison: <br>" >> $OUTPUT
$MYSQL --execute="select mailing_list, count(*) as signatures, sum(pass) as passed, 100*sum(pass)/count(*) as '%pass' from signatures join messages on messages.id = signatures.message group by messages.mailing_list" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>ADSP policies found and failures: <br>" >> $OUTPUT
$MYSQL --execute="select sum(adsp_found) as found, sum(adsp_unknown) as 'unknown', sum(adsp_all) as 'all', sum(adsp_discardable) as 'discardable', sum(adsp_fail) as 'failed' from messages" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Author vs. third-party signatures: <br>" >> $OUTPUT
$MYSQL --execute="select count(*) as 'author sigs', sum(pass) as 'passed' from signatures join messages on messages.id = signatures.message where messages.from_domain = signatures.domain" >> $OUTPUT
$MYSQL --execute="select count(*) as 'third-party sigs', sum(pass) as 'passed' from signatures join messages on messages.id = signatures.message where not messages.from_domain = signatures.domain" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Signed header field frequency: <br>" >> $OUTPUT
$MYSQL --execute="select headernames.name, count(signed_headers.id) as count from signed_headers join headernames on headernames.id = signed_headers.header group by signed_headers.header order by count(signed_headers.id) desc" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Count of unique signing domains in sample: <br>" >> $OUTPUT
$MYSQL --execute="select count(distinct from_domain) as domains from messages where anonymized = 0" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Top 10 signing domains by signature count: <br>" >> $OUTPUT
$MYSQL --execute="select domains.name, sum(sigcount) as signatures from messages join domains on domains.id = messages.from_domain where anonymized = 0 group by from_domain order by sum(sigcount) desc limit 10" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Top 10 signing domains by passing signature percentage: <br>" >> $OUTPUT
$MYSQL --execute="select domains.name, count(*) as signatures, 100*sum(pass)/count(*) as pct_passed from signatures join domains on domains.id = signatures.domain join messages on signatures.message = messages.id where messages.anonymized = 0 group by signatures.domain order by pct_passed desc, signatures desc limit 10" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Top 10 signing domains by failed signature percentage: <br>" >> $OUTPUT
$MYSQL --execute="select domains.name, count(*) as signatures, 100-100*sum(pass)/count(*) as pct_failed from signatures join domains on domains.id = signatures.domain join messages on signatures.message = messages.id where messages.anonymized = 0 and signatures.ignored = 0 group by signatures.domain order by pct_failed desc, signatures desc limit 10" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Correlation of IP addresses to signed From: domains: <br>" >> $OUTPUT
$MYSQL --execute="select ipaddr, count(distinct from_domain) as domains from messages where sigcount > 0 and anonymized = 0 group by ipaddr order by domains desc limit 10" >> $OUTPUT
echo "</p>" >> $OUTPUT

echo "<p>Correlation of Received: count to signature successes: <br>" >> $OUTPUT
$MYSQL --execute="select received_count, sum(sigcount) as 'total sigs', sum(signatures.pass) as 'passed', 100*sum(signatures.pass)/sum(sigcount) as '% pass' from messages join signatures on signatures.message = messages.id where received_count > 0 and sigcount > 0 group by received_count" >> $OUTPUT
echo "</p>" >> $OUTPUT

# output a footer
cat >> $OUTPUT << EOF
  </body>
</html>
EOF

# all done!
exit 0
